version: "3"
services:
    app:
        container_name: webrtc_chat_hash
        restart: unless-stopped
        build: ./
        ports:
            - "8000:8000"
            - "433:433"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
